import NavBar from "@/_components/navbar/navbar";
import "./core.css"
import "./globals.css";
import { Providers } from "@/_lib/Providers";


export const metadata = {
  title: {
    default: "Zespół Szkół Technicznych im. 10 Pułku Piechoty w Łowiczu",
    template: " ZST | %s"
  },
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  }
};

export default function RootLayout({ children }) {


//  Dodajemy suppressHydrationWarning do <html>, 
//  ponieważ nasz skrypt będzie zmieniał klasy/atrybuty 
//  zaraz po załadowaniu strony.
  return (
    <html lang="pl">
      <body suppressHydrationWarning
        className={''}
      >
        <Providers>
          <NavBar></NavBar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
