import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "./temp.css"
import "./temp2.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Zespół Szkół Technicznych im. 10 Pułku Piechoty w Łowiczu",
    template: " ZST | %s"
  },
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased visual-refresh theme-dark`}
        style={{"--custom-theme-base-color-amount": "100%"}}
      >
        {children}
      </body>
    </html>
  );
}
