import Menu from "@/_components/Menu";
import "./core.css"
import "./globals.css";
import { Providers } from "@/_lib/Providers";
import {Roboto,Roboto_Flex,Roboto_Mono,JetBrains_Mono,} from 'next/font/google'
import Footer from "@/_components/Footer";
import ScrollController from "@/_lib/scrollControler";

export const metadata = {
  title: {
    default: "Zespół Szkół Technicznych im. 10 Pułku Piechoty w Łowiczu",
    template: " ZST | %s"
  },
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  }
};

const roboto = Roboto({subsets: ['latin'],variable: '--font-roboto',})
const robotoFlex = Roboto_Flex({
  subsets: ['latin'],
  variable: '--font-roboto-flex',
  axes: ['wght', 'wdth', 'GRAD', 'opsz'],
})
const robotoMono = Roboto_Mono({subsets: ['latin'],variable: '--font-roboto-mono',})
const jetBrainsMono = JetBrains_Mono({subsets: ['latin'],variable: '--font-jetBrainsMono',})

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body suppressHydrationWarning
        className={`${roboto.variable}${robotoFlex.variable}${robotoMono.variable}`}
        style={{transition: 'none', overflowX: 'hidden' }}
      >
        <ScrollController/>
        <Providers>
          <Menu/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
